### ISSUE TITLE
Add decorator for ensuring game not over for hit/stand

### ISSUE THREAD

**Issue by Vlek** [Vlek/Blackjack#23]
Right now, both functions in the Blackjack game object are doing their conditional checking to ensure that the game is still going in order to know whether to continue with the function call. This would be better as a decorator, like `@_ensureGameStatePlaying`

**Comment by Vlek** [comment]
This is apparently kinda difficult.

Found a good answer here: https://stackoverflow.com/questions/11731136/class-method-decorator-with-self-arguments

So you can technically get out the object instance to do stuff with, but I was getting an error:
```
Traceback (most recent call last):
  File ".../blackjack-Jg634NG2-py3.10/bin/hit", line 3, in <module>
    from blackjack.console import hit
  File "Blackjack/src/blackjack/console.py", line 10, in <module>
    from blackjack.blackjack import Blackjack, GameState
  File "Blackjack/src/blackjack/blackjack.py", line 67, in <module>
    class Blackjack:
  File "Blackjack/src/blackjack/blackjack.py", line 92, in Blackjack
    @__ensureGameStatePlaying
NameError: name '_Blackjack__ensureGameStatePlaying' is not defined. Did you mean: '__ensureGameStatePlaying'?
```

I am too lazy to work this out right now. I will revisit this because it's honestly much simpler to deal with with my `isGameOver` helper method than do this.
